'use strict';

/**
 * @author Wouter Van den Broeck for iMinds.be [wouter.vandenbroeck@iminds.be]
 * @copyright 2016, iMinds v.z.w.
 */

import duxisActionTypes from 'cargo-lib/html/system/actionTypes'

const foggActionTypes = {
  ADD_REWARD: 'fogg/ADD_REWARD',
  ADD_REWARD_SUCCESS: 'fogg/ADD_REWARD_SUCCESS',
  ADD_REWARD_FAILED: 'fogg/ADD_REWARD_FAILED',

  DELETE_REWARD: 'fogg/DELETE_REWARD',
  DELETE_REWARD_FAILED: 'fogg/DELETE_REWARD_FAILED',
  DELETE_REWARD_SUCCESS: 'fogg/DELETE_REWARD_SUCCESS',

  FETCH_REWARDS: 'fogg/FETCH_REWARDS',
  FETCH_REWARDS_FAILED: 'fogg/FETCH_REWARDS_FAILED',
  FETCH_REWARDS_SUCCESS: 'fogg/FETCH_REWARDS_SUCCESS',

  TEST_REWARD: 'fogg/TEST_REWARD',
  TEST_REWARD_FAILED: 'fogg/TEST_REWARD_FAILED',
  TEST_REWARD_SUCCESS: 'fogg/TEST_REWARD_SUCCESS',

  UPDATE_REWARD: 'fogg/UPDATE_REWARD',
  UPDATE_REWARD_FAILED: 'fogg/UPDATE_REWARD_FAILED',
  UPDATE_REWARD_SUCCESS: 'fogg/UPDATE_REWARD_SUCCESS',

  SEND_LOG: 'fogg/SEND_LOG',
  SEND_LOG_SUCCESS: 'fogg/SEND_LOG_SUCCESS',
  SEND_LOG_FAILED: 'fogg/SEND_LOG_FAILED',

  FETCH_LOGS: 'fogg/FETCH_LOGS',
  FETCH_LOGS_FAILED: 'fogg/FETCH_LOGS_FAILED',
  FETCH_LOGS_SUCCESS: 'fogg/FETCH_LOGS_SUCCESS',

  TEST_LOG: 'fogg/TEST_LOG',
  TEST_LOG_FAILED: 'fogg/TEST_LOG_FAILED',
  TEST_LOG_SUCCESS: 'fogg/TEST_LOG_SUCCESS',

  ADD_RULE: 'fogg/ADD_RULE',
  ADD_RULE_SUCCESS: 'fogg/ADD_RULE_SUCCESS',
  ADD_RULE_FAILED: 'fogg/ADD_RULE_FAILED',

  FETCH_RULES: 'fogg/FETCH_RULES',
  FETCH_RULES_FAILED: 'fogg/FETCH_RULES_FAILED',
  FETCH_RULES_SUCCESS: 'fogg/FETCH_RULES_SUCCESS',

  UPDATE_RULE: 'fogg/UPDATE_RULE',
  UPDATE_RULE_FAILED: 'fogg/UPDATE_RULE_FAILED',
  UPDATE_RULE_SUCCESS: 'fogg/UPDATE_RULE_SUCCESS',


  DELETE_USER: 'fogg/DELETE_USER',
  DELETE_USER_FAILED: 'fogg/DELETE_USER_FAILED',
  DELETE_USER_SUCCESS: 'fogg/DELETE_USER_SUCCESS',

  ADD_USER: 'fogg/ADD_USER',
  ADD_USER_FAILED: 'fogg/ADD_USER_FAILED',
  ADD_USER_SUCCESS: 'fogg/ADD_USER_SUCCESS',

  EDIT_USER: 'fogg/EDIT_USER',
  EDIT_USER_FAILED: 'fogg/EDIT_USER_FAILED',
  EDIT_USER_SUCCESS: 'fogg/EDIT_USER_SUCCESS',

  FETCH_ROLES: 'fogg/FETCH_ROLES',
  FETCH_ROLES_SUCCESS: 'fogg/FETCH_ROLES_SUCCESS',
  FETCH_ROLES_FAILED: 'fogg/FETCH_ROLES_FAILED',

  FETCH_USER: 'fogg/FETCH_USER',
  FETCH_USER_FAILED: 'fogg/FETCH_USER_FAILED',
  FETCH_USER_SUCCESS: 'fogg/FETCH_USER_SUCCESS',

  FETCH_USERS: 'fogg/FETCH_USERS',
  FETCH_USERS_FAILED: 'fogg/FETCH_USERS_FAILED',
  FETCH_USERS_SUCCESS: 'fogg/FETCH_USERS_SUCCESS',

  INVALIDATE_USERS: 'fogg/INVALIDATE_USERS',
  SHOW_USER: 'fogg/SHOW_USER'
};

export default {
  ...duxisActionTypes,
  ...foggActionTypes
}
